### ISSUE TITLE
Having trouble running on Intel Edison Platform

### ISSUE THREAD

**Issue by phixMe** [landlessness/node-BNO055#4]
Hi, I am having some trouble with the following mysterious error that involves the i2c.node file, which is not readable.

ERROR: module.js:356
  Module._extensions[extension](this, filename);
                               ^
ERROR: Error: /home/root/.node_app_slot/node_modules/node-BNO055/node_modules/i2c/build/Release/i2c.node: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/root/.node_app_slot/node_modules/node-BNO055/node_modules/i2c/lib/i2c.coffee:8:10)
    at Object.<anonymous> (/home/root/.node_app_slot/node_modules/node-BNO055/node_modules/i2c/lib/i2c.coffee:164:4)
    at Module._compile (module.js:456:26)
    at Object.require.extensions..coffee (/home/root/.node_app_slot/node_modules/node-BNO055/node_modules/i2c/node_modules/coffee-script/lib/coffee-script/coffee-script.js:22:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Thanks,
Peter

**Comment by phixMe** [comment]
I was able to figure it out by replacing the '^' with '~' in the package.json file for the i2c dependency. I was picking up a later version and receiving a conflict
